### ISSUE TITLE
Players being disconnected due to server stopping or restarting doesn't get logged by blockbot

### ISSUE THREAD

**Issue by CalXee** [QuiltServerTools/BlockBot#10]
Quite trivial, since server stopping already implies everyone gets kicked, but nevertheless it feels like something that should get logged but isn't.
![Screenshot 2021-06-03 120059](https://user-images.githubusercontent.com/68349758/120675920-81000280-c463-11eb-9f40-dd8095d66e16.png)

**Comment by yitzy299** [comment]
Will add a manual bit of logic to get around this
