### ISSUE TITLE
Feature request: able to use Groovy commands using in game chat

### ISSUE THREAD

**Issue by CalXee** [QuiltServerTools/BlockBot#12]
Oh c'mon, this screenshot is just pure sadness. You guys gotta consider this.

![Screenshot 2021-06-03 221722](https://user-images.githubusercontent.com/68349758/120736081-9ef85200-c4b9-11eb-990f-0e53afa57e6c.png)

**Comment by PotatoPresident** [comment]
This would be groovy's issue. It most likely is programmed to ignore commands from other bots.
