### ISSUE TITLE
Feature request: the ability to use discord text styles and have it show up in game

### ISSUE THREAD

**Issue by CalXee** [QuiltServerTools/BlockBot#16]
Typing ~~Text~~ should result in a crossed out text in game, same with bold, etc.

Something should be done for the Spoilers text style, since Minecraft doesn't support anything similar to that. (Or any other styles Minecraft doesn't support that I am not aware of)

May be rejected because this lets you bypass the vanilla limitation of typing these types of text from in game, but still. I think that would be a welcome feature. Perhaps a config to disable that?

**Comment by Patbox** [comment]
You can recreate spoilers with hover text
