### ISSUE TITLE
[Feature Request] Ability to link your Discord account to your Minecraft account

### ISSUE THREAD

**Issue by Southpaw1496** [QuiltServerTools/BlockBot#17]
Linking can either be optional or required. If optional it's initiated by an in-game command, if non-optional, it's started on join.

When the user runs the command/gets kicked, they are sent a code (via command or kick message), which they can then DM to the Discord bot, linking their accounts. Among other things, this is more secure than a simple `!whitelist` command because players can only "whitelist" accounts that they have access to. It also avoids having to use the vanilla whitelist, which, as discussed in Discord, is cursed. 

If forcing players to have linked accounts to join is on, this behaviour is disabled if the whitelist is enabled, so you can block people from joining even if their account is linked, and players on the whitelist don't have to have their account linked to join. This would be useful for quickly setting the server to staff-only while doing maintenance. There could also be an option to always let whitelisted players and/or ops through, even if the player is not linked.

Linked accounts get the following features (preferably configurable):
- Players with linked accounts can get a role on Discord
- Players can only join if they have a given role assigned (useful for a Twitch/Patreon server, for example, obviously only works if account linking is forced)
- Players can only join if they are in a specific guild (or in one of a list of guilds)
- Linked players can have their Discord nickname set to their Minecraft username
- Roles on Discord can sync to a LuckPerms etc. permission group.
- Minecraft Bans and Discord bans can sync.

**Comment by elhertz** [comment]
+1
A feature to sync an account and link discord roles to LuckPerms would be nice.

**Comment by Southpaw1496** [comment]
Uhhh
> Roles on Discord can sync to a LuckPerms etc. permission group.

This is planned for Blockbot 2, by the way. Updates are posted in Discord.

**Comment by elhertz** [comment]
> Uhhh I did say " Roles on Discord can sync to a LuckPerms etc. permission group"

I know. I was just sharing my opinion on that specific suggestion you made.
