### ISSUE TITLE
Whitelist command doesnt appear to check for empty arguments.

### ISSUE THREAD

**Issue by kingultron99** [QuiltServerTools/BlockBot#27]
When performing `!whitelist` without the necessary arguments, the bot will proceed to whitelist "whitelist".
Not sure if this could be from the way the bot processes the message.

however, a check to see if the message doesn't have any arguments and responding appropriately might be nice :D

likewise, has a `!whitelist remove` subcommand been considered?

either way, this is cool stuff. thanks for your hard work!

**Comment by Southpaw1496** [comment]
There is a rewrite being worked on which will include a full-blown account linking system (similar to the Spigot plugin DiscordSRV) so the command is not as needed anymore, but I believe this is being addressed if they're not getting rid of the command altogether.

**Comment by kingultron99** [comment]
ah righto. looking forward to see the update!
