### ISSUE TITLE
Restarting a server doesn't get logged in discord as "Server Stopped"

### ISSUE THREAD

**Issue by CalXee** [QuiltServerTools/BlockBot#3]
When using a server hosting service (I've tested on bisect hosting), restarting a server does not get logged as "Server Stopped". Only when the server starts again does it log "Server Started".

I pressed the restart button on the server control panel and restarts don't get logged.

**Comment by yitzy299** [comment]
Sadly there's nothing I can do about this - it is likely your host waiting on just the MC threads before killing, not the bot threads as well

**Comment by yitzy299** [comment]
I have confirmation of this issue, and believe I have a solution
