### ISSUE TITLE
Not fetching translations for modded deaths

### ISSUE THREAD

**Issue by EvilSquirrelGuy** [QuiltServerTools/BlockBot#4]
I have a server running with the origins mod, and when someone gets a non-vanilla death (such as drowning from air), BlockBot only sends the translation key.
![image](https://user-images.githubusercontent.com/52577747/119218197-118b2a00-bad7-11eb-94a5-11ac539a1f10.jpeg)

**Comment by yitzy299** [comment]
Origins need to bundle their translations in the bundled datapack
