### ISSUE TITLE
Incompatible with Create Mod

### ISSUE THREAD

**Issue by Alkiasan** [QuiltServerTools/BlockBot#42]
Seems to be caused by using Adventure-platform as a dependency, causes crashes whenever BlockBot and Create Refabricated are running together

Refer to:
https://github.com/Fabricators-of-Create/Create/issues/150
https://github.com/Fabricators-of-Create/Create/issues/117

**Comment by Alkiasan** [comment]
That version's for 1.18.2, so I can't try it until Create updates to 1.18.2, but i'll test then notify you once it does ^^

**Comment by Oliver-makes-code** [comment]
> Try [this](https://github.com/QuiltServerTools/BlockBot/actions/runs/1949098551)

With dependency overrides to make it compatible with 1.18, it works perfectly

**Comment by Alkiasan** [comment]
Alright, i'll close the issue in that case ^^
