### ISSUE TITLE
Feature Request: Stats in channel description

### ISSUE THREAD

**Issue by EvilSquirrelGuy** [QuiltServerTools/BlockBot#5]
Having server stats in the channel description (such as players online, uptime etc.) configured for chat messages, to be able to see information at a glance

**Comment by CalXee** [comment]
It already shows player online in the bot's "Playing a game" info in the bot's profile. Maybe adding uptime to that and make it configurable with the config file.

**Comment by yitzy299** [comment]
Afraid this won't be doable thanks to discord API limitations

**Comment by Tom-The-Geek** [comment]
What limitations?

**Comment by yitzy299** [comment]
Rate limiting
