### ISSUE TITLE
Support for vanish mods

### ISSUE THREAD

**Issue by Genau6502** [QuiltServerTools/BlockBot#69]
### Is your feature request related to a problem?

In vanish, /playerlist and the count in the status field on discord still includes the player count including players in vanish.

![image](https://github.com/QuiltServerTools/BlockBot/assets/66269211/3daeb9bc-2b2a-4cb4-aec7-03ddb1daefff)

### Describe the solution you'd like.

Option in the API to provide a playerlist to allow vanish mods to remove such players from the display.

### Describe alternatives you've considered.

N/A

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by DrexHD** [comment]
Change the config `[MemberCommands.PlayerList]` to `title = "%vanish:online%/%server:max_players%"` (use the vanish placeholder). Vanished players should already be excluded from the list.
